### ISSUE TITLE
Score does not match status / non-integer values for score

### ISSUE THREAD

**Issue by madelhorius** [xzhub/LTR_Finder#6]
Hi
I ran LTR_finder on an assembly and got some suspicious results. According to your manual score should be integer but I also get scores of 6.5, 7.5 and 8.5. How can this occur?
Additionally the number of 1s in the status should match the score, shouldn't it? I have some LTRs for which according to their status only 8 features were found, however they still get a score of 10 (see output below). Is there something else included in the score?
 
Part of the standard output:
Location : 3640988 - 3660093 Len: 19106 Strand:+
Score    : 10 [LTR region similarity:1]
Status   : 11111111000

Thanks!
Marius

**Comment by xzhub** [comment]
Just noticed this issue. If you've found the solution, please let me know, I don't have a clue on this for now.

**Comment by xzhub** [comment]
Please reopen if you are still on it. Sorry for the late reply.
