### ISSUE TITLE
Can you please add a LICENSE file?

### ISSUE THREAD

**Issue by oushujun** [xzhub/LTR_Finder#7]
Hello,

There is some intentions to make a conda version of the LTR_FINDER software, which requires a specified license. Can you please add a LICENSE file to the repo? If possible, adding a [GPLv3](https://github.com/bioinfolabmu/GenericRepeatFinder/blob/master/license.txt) license will greatly help! GPLv3 is a copy-left license allowing both non-commercial and commercial use.

Best,
Shujun

**Comment by Juke34** [comment]
Dear @xzhub, do you allow redistribution of your tool? If yes we could package it into conda.   
As mentioned by @oushujun adding a clear licence in your repo will greatly help: here a list of available licenses: [https://opensource.org/licenses/alphabetical](https://opensource.org/licenses/alphabetical)

**Comment by xzhub** [comment]
MIT license added.
