### ISSUE TITLE
Size limit binary code request

### ISSUE THREAD

**Issue by huwl404** [xzhub/LTR_Finder#8]
Hi;
I ran LTR-Finder and found that submit sequence was allowed in 50000000 bytes, but my genome is very large (about 10 Gb) and the smallest sequence is 760 Mb, I wondering if you could offer the executive binary code  as described in your manual for very large size sequences. Thank you very much!

Yours
Yi Wang, PhD candidate
Sichuan University
x_wangyier@163.com

**Comment by xzhub** [comment]
Binary file could be found in this folder: https://github.com/xzhub/LTR_Finder/tree/master/build
