### ISSUE TITLE
ps_scan error

### ISSUE THREAD

**Issue by a7032018** [xzhub/LTR_Finder#9]
I am using LTR_Finder with -a option, and it gives me an error...
Program    : LTR_FINDER
Version    : 1.07

/usr/bin/env: ‘perl\r’: No such file or directory
execute ps_scan error

I was able to execute ps_scan.pl without problem. It could relate to the Perl setting. Any advises are appreciated!

**Comment by xzhub** [comment]
Please try to convert all scripts into linux text format to remove the extral '\r'.
If you are in Linux, run this command for all files:

```
dos2unix *
```

**Comment by a7032018** [comment]
> dos2unix *

It runs flawlessly. Thanks!
